apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: dag-model-serving-test-7
spec:
  entrypoint: model-repo-pull             # 시작점 위치
  volumeClaimTemplates:                 # define volume, same syntax as k8s Pod spec
  - metadata:
      name: workdir                     # name of volume claim
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi     
  templates:
  - name: ls-template
    inputs:
      parameters:
      - name: path
    container:
      image: alpine:latest
      command: ["ls", "-al", "{{inputs.parameters.path}}"]
    
  - name: git-template
    inputs:
      parameters:
      - name: branch
      - name: remote_repo
    container:
      image: brightfly/workflow:git
      command: ["git", "clone",  "-b", "{{inputs.parameters.branch}}", "{{inputs.parameters.remote_repo}}", "/workdir"]
      volumeMounts:                     # same syntax as k8s Pod spec
      - name: workdir
        mountPath: /workdir
  - name: dvc-template
    container:
      image: brightfly/workflow:git
      command: [sh, -c]
      args: ["cd /workdir && dvc pull"]
      volumeMounts:                     # same syntax as k8s Pod spec
      - name: workdir
        mountPath: /workdir

  - name: bentoml-pack-template
    container:
      image: brightfly/workflow:bentoml.torch
      command: [sh, -c]
      args: ["cp /root/*.py /workdir && cd /workdir && python bento_pack.py"]
      volumeMounts:                     # same syntax as k8s Pod spec
      - name: workdir
        mountPath: /workdir

  - name: model-repo-pull
    dag:
      tasks:
      - name: git-pull            
        template: git-template
        arguments:                
          parameters: [{name: branch, value: "train/211110"}, {name: remote_repo, value: "https://github.com/mojokb/onboard-mlops-model.git"}]
      - name: dvc-pull
        template: dvc-template
        dependencies: [git-pull]
      - name: bentoml-packing-model
        template: bentoml-pack-template
        dependencies: [dvc-pull]
      - name: list-model-pack
        dependencies: [bentoml-packing-model]
        template: ls-template
        arguments:  
          parameters: [{name: path, value: "/workdir/bentoml"}]
        
      