apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mnist-test-image
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
