apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: dag-model-serving-bd110ee5568a43e669a7dd84ed3a4bc838aed8be
spec:
  arguments:
    parameters:
    - name: servicename
      value: onboard-mlops-model
    - name: branch
      value: train/2021-1120
    - name: remote_repo
      value: https://github.com/mojokb/onboard-mlops-model.git
    - name: image
      value: 192.168.64.5:30000/bentoml-torch:bd110ee5568a43e669a7dd84ed3a4bc838aed8be
  entrypoint: model-repo-pull
  podGC:
    labelSelector:
      matchLabels:
        should-be-deleted: "true"
    strategy: OnWorkflowCompletion
  templates:
  - container:
      args:
      - -R
      - '{{inputs.parameters.path}}'
      command:
      - ls
      image: alpine:latest
      volumeMounts:
      - mountPath: /workdir
        name: workdir
    inputs:
      parameters:
      - name: path
    metadata:
      labels:
        should-be-deleted: "false"
    name: ls-template
  - container:
      args:
      - git clone -b {{workflow.parameters.branch}} {{workflow.parameters.remote_repo}}
        /workdir && cd /workdir && dvc pull
      command:
      - sh
      - -c
      image: brightfly/workflow:git
      volumeMounts:
      - mountPath: /workdir
        name: workdir
    metadata:
      labels:
        should-be-deleted: "true"
    name: gitdvc-template
  - container:
      args:
      - cp /workdir/bento_pack/*.py /workdir && cd /workdir && python bento_pack.py
      command:
      - sh
      - -c
      image: brightfly/workflow:bentoml.torch
      volumeMounts:
      - mountPath: /workdir
        name: workdir
    metadata:
      labels:
        should-be-deleted: "true"
    name: bentoml-pack-template
  - container:
      args:
      - --cache=true
      - --context=/workdir/bentoml
      - --destination={{workflow.parameters.image}}
      command:
      - /kaniko/executor
      image: gcr.io/kaniko-project/executor
      volumeMounts:
      - mountPath: /workdir
        name: workdir
    metadata:
      labels:
        should-be-deleted: "true"
    name: kaniko-template
  - metadata:
      labels:
        should-be-deleted: "true"
    name: test-model
    script:
      command:
      - python
      image: brightfly/workflow:bentoml.torch
      source: "import sys\nsys.path.append(\"/workdir\")\nfrom src.models.test_model
        import TestModel\ntest_model = TestModel()\ntest_model.load_model(\"/workdir/models/model.pt\")\nprint(test_model.test())
        \      \n"
      volumeMounts:
      - mountPath: /workdir
        name: workdir
      workingDir: /workdir
  - name: deploy-knative-template
    resource:
      action: create
      manifest: "apiVersion: serving.knative.dev/v1 \nkind: Service\nmetadata:\n  name:
        {{workflow.parameters.servicename}}\nspec:\n  template:\n    spec:\n      containers:\n
        \       - image: {{workflow.parameters.image}}\n          ports:\n            -
        containerPort: 5000\n          livenessProbe:\n            httpGet:\n              path:
        /healthz\n            initialDelaySeconds: 3\n            periodSeconds: 5\n
        \         readinessProbe:\n            httpGet:\n              path: /healthz\n
        \           initialDelaySeconds: 3\n            periodSeconds: 5\n            failureThreshold:
        3\n            timeoutSeconds: 60         \n"
  - dag:
      tasks:
      - name: gitdvc-pull
        template: gitdvc-template
      - dependencies:
        - gitdvc-pull
        name: test-model
        template: test-model
      - dependencies:
        - test-model
        name: bentoml-packing-model
        template: bentoml-pack-template
        when: '{{tasks.test-model.outputs.result}} > 0.90'
      - arguments:
          parameters:
          - name: path
            value: /workdir/bentoml
        dependencies:
        - bentoml-packing-model
        name: list-model-pack
        template: ls-template
      - dependencies:
        - bentoml-packing-model
        name: containerize
        template: kaniko-template
      - dependencies:
        - containerize
        name: deploy
        template: deploy-knative-template
    name: model-repo-pull
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
