apiVersion: serving.knative.dev/v1 
kind: Service
metadata:
  name: serving-test
spec:
  template:
    spec:
      containers:
        - image: 192.168.64.5:30000/bentoml-torch:edb342cbb828f58c1314ec94c4d038efcaa5b3a0
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /healthz
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 60              
