apiVersion: serving.knative.dev/v1 
kind: Service
metadata:
  name: serving-test
spec:
  template:
    spec:
      containers:
        - image: 192.168.54.5:30000/bentoml:test
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /healthz
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 60              
