apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: dag-bentoml-containerize
spec:
  entrypoint: containerize             # 시작점 위치
  templates:
  - name: git
    inputs:
      parameters:
      - name: branch
      - name: remote_repo
    container:
      image: brightfly/workflow:git
      command: ["git", "clone",  "-b", "", ""]
  - name: containerize   
    dag:
      tasks:
      - name: git-pull            
        template: git            # 위에서 정의한 echo template을 이용하여
        arguments:                # 이때 A라는 파라미터를 전달합니다.
          parameters: [{name: branch, value: "train/211110"}, {name: remote_repo, value: "https://github.com/mojokb/onboard-mlops-model.git"} ]
